### ISSUE TITLE
All of these non-break spaces are unnecessary

### ISSUE THREAD

**Issue by jsiarto** [JingkunXu/mi349_blog#1]
https://github.com/JingkunXu/mi349_blog/blob/34456b72f8ef099f8230a668d7d71313e52230f6/index.html#L13

**Comment by JingkunXu** [comment]
Do you mean that I should use <p>comment</p> instead of
<p>
 <comment>
</p>?
If this issue does not break the rule, I would say that I just want to make the paragraph clear to me beacuse I might need to add other elements like table this week, it would help me to keep my code reading organized.  If it did affect the content, I would change that.

**Comment by JingkunXu** [comment]
Oh the website did not show some of my comment.
Do I have to use p comment p instead of
p
 comment
p?
